### ISSUE TITLE
Add descriptions to your repos

### ISSUE THREAD

**Issue by Dasonk** [trinker/lexicon#13]
Add some descriptions to your repositories you bum

**Comment by trinker** [comment]
Do people really look at or use them?  What do the buy me?  SEO?

**Comment by Dasonk** [comment]
Well github recently started showing the repo description when people that you follow star a repo.  So it could entice people to actually view the repo instead of skipping over it if the description actually sounds like something they care about.  I'm guessing it might buy a touch of SEO too but the lack of description on your repos was noticeable on my timeline (or whatever it's called) since those repos were the only ones without descriptions.

**Comment by trinker** [comment]
fair point thanks
