### ISSUE TITLE
can't find hash_sentiment_inquirer in the package

### ISSUE THREAD

**Issue by lannhan2018** [trinker/lexicon#18]
Hi Tyler,

I notice that the description mentions the `hash_sentiment_inquirer` table as the Polarity Lookup Table using Inquirer (I presume that it's referring to the Harvard's General Inquirer). However, I can't seem to find it in the package.

````
> lexicon::hash_sentiment_inquirer
Error: 'hash_sentiment_inquirer' is not an exported object from 'namespace:lexicon'
````

I also tried `lexicon::available_data()` but can't seem to find it either.

Am I missing something? 

Thank you for your help,

Ken.

**Comment by trinker** [comment]
It has been removed as I could not find the appropriate licensing. for this data set.
