### ISSUE TITLE
profanity_google and profanity_voh_ahn data files removed in latest commit

### ISSUE THREAD

**Issue by blakiseskream** [trinker/lexicon#19]
It appears as if `profanity_google` and `profanity_von_ahn` were removed for the `DESCRIPTION` file in the latest commit.

Was this intentional?

If people stumble upon this installing the previous commit brings the data in

```r
devtools::install_github("trinker/lexicon", ref = "bd0e3901de45d5986d32d6e45670ac39b622a8d1")
```

**Comment by blakiseskream** [comment]
It appears when [this file](https://github.com/trinker/lexicon/commit/7f605c428e2779be0c3e139cfa9ac147eedf85f3#diff-35ba4a2677442e210c23a00a5601aba3L26) was cleaned up they were deleted, causing `roxygen` to delete the `.R` files I assume,

**Comment by trinker** [comment]
These were removed because the licensing for these data sets wasn't clear.  If you can find clear licensing that can be included they can return.
