### ISSUE TITLE
NA within the dataset

### ISSUE THREAD

**Issue by martincadek** [trinker/lexicon#34]
Hi. Not sure whether this was intentional but I found one NA within the dataset. Try running `as.vector(freq_first_names$Name[3300:3305])` which shows the location of the NA. This refers to version ‘1.3.0’. This might be important as it requires removing such values prior to creating other objects, e.g.: dictionaries.

**Comment by trinker** [comment]
Thank you for the issue.  This is an error I believe.  I'll have a look
soon.
