### ISSUE TITLE
indonesian nrc

### ISSUE THREAD

**Issue by sarahmnalifa** [trinker/lexicon#35]
As i know that NRC Emolex is available in 40+ languages including Indonesian language. is indonesian laguage of NRC also available on this package?

**Comment by trinker** [comment]
Sorry no...in fact we are looking to remove nrc internally and rely on textdata packagehttps://github.com/trinker/lexicon/issues/33

**Comment by sarahmnalifa** [comment]
how about sentowordnet? is there any way to add indonesian sentiwordnet into this package?
