### ISSUE TITLE
trouble with exports - 'hash_sentiment'

### ISSUE THREAD

**Issue by d45** [trinker/lexicon#8]
I can't run the sentiment* functions. 

>pacman::p_load_current_gh("trinker/lexicon", "trinker/sentimentr")
>sentiment_by(sam_i_am, by = NULL)
Error: 'hash_sentiment' is not an exported object from 'namespace:lexicon'

**Comment by trinker** [comment]
Give it a try now.  I'm in the process of updating both packages.  Just pushed the new lexicon to CRAN.

**Comment by d45** [comment]
OK. Excellent. The update works fine. Thanks!
